### Problem 1
Create a NumPy array of list(5,3,8,9,2)

In [88]:
import numpy as np
my_array = np.array([5,3,8,9,2])
my_array

array([5, 3, 8, 9, 2])

In [110]:
type(my_array)

numpy.ndarray

### Problem 2

Make a range of numbers using numpy where the numbers range between 0 and 130, but are incremented by 3.

In [120]:
np.arange(0,130,3)

array([  0,   3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36,
        39,  42,  45,  48,  51,  54,  57,  60,  63,  66,  69,  72,  75,
        78,  81,  84,  87,  90,  93,  96,  99, 102, 105, 108, 111, 114,
       117, 120, 123, 126, 129])

Expected Output: 

array(
[  0,   3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36,
        39,  42,  45,  48,  51,  54,  57,  60,  63,  66,  69,  72,  75,    
               78,  81,  84,  87,  90,  93,  96,  99, 102, 105, 108, 111, 114,        
              117, 120, 123, 126, 129])

### Problem 3

Make 8 lists of 5 elements containing a 1. for each element.

In [125]:
np.ones((8,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Expected Output:

array([

       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],    
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Problem 4

Create an 8x8 identity matrix using strictly numpy. Use google to your advantage!

In [126]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

Now add up multiple 8x8 identity matrices so that the resulting matrix is still 8x8, but contains a diagonal of 9s

In [139]:
numb = 0
for x in range(9):
    numb += np.eye(8)
numb

array([[9., 0., 0., 0., 0., 0., 0., 0.],
       [0., 9., 0., 0., 0., 0., 0., 0.],
       [0., 0., 9., 0., 0., 0., 0., 0.],
       [0., 0., 0., 9., 0., 0., 0., 0.],
       [0., 0., 0., 0., 9., 0., 0., 0.],
       [0., 0., 0., 0., 0., 9., 0., 0.],
       [0., 0., 0., 0., 0., 0., 9., 0.],
       [0., 0., 0., 0., 0., 0., 0., 9.]])

## Discussion Section

Cool Jupyter command: 
If you add a `%time` command at the top of a cell, it will show you how long your code block takes to run

Try it out

In [105]:
%time

print('This is how long this code block takes to run^')

CPU times: user 3 µs, sys: 1 µs, total: 4 µs
Wall time: 6.2 µs
This is how long this code block takes to run^


When we compare the runtime of a numpy array being iterated over vs. a regular Python list iterated by a for loop. We find that Numpy is actually faster to run. Discuss with your table why this is. 

Try using the for loop on the Numpy array and test how long it takes to run the code block.

In [98]:
np_array = np.array([2, 6, 1, 9, 10, 3, 27])

In [99]:
%time
index = np.where((np_array >= 5) & (np_array <= 10))
index

CPU times: user 4 µs, sys: 1e+03 ns, total: 5 µs
Wall time: 8.11 µs


(array([1, 3, 4]),)

In [100]:
reg_array = [2, 6, 1, 9, 10, 3, 27]

In [101]:
%time
for num in reg_array:
    if (num >= 5) & (num <=10):
        print(reg_array.index(num))

CPU times: user 5 µs, sys: 1e+03 ns, total: 6 µs
Wall time: 10 µs
1
3
4
